### ISSUE TITLE
ContextManager for LaTeX files to handle cleanup in place

### ISSUE THREAD

**Issue by mpacer** [mpacer/jupyterlab-latex#2]
It would be nice to have a context manager that would clean up any and only the accessory files created by running LaTeX. 

This can likely be accomplished by 
1. creating a representation of the local directory structure prior to running LaTeX
2. creating a representation of the local directory structure after running LaTeX
3. excluding the new pdf, removing all of the discrepancies between the states at 1. and 2.

If anyone knows of a likely issue related to that I'd be interested to know more about it.

**Comment by ian-r-rose** [comment]
Closed by 7675b92158e67fdd4748aef455421c5cdf0389c8
