### ISSUE TITLE
Handle directories

### ISSUE THREAD

**Issue by ian-r-rose** [mpacer/jupyterlab-latex#4]
The file path logic is broken for LaTeX projects in subdirectories. This is fixed client-side by #3, but it also needs to be fixed server side. We need to `cd` into the appropriate directory and make sure the paths for the `.pdf`, `.tex`, and `.log` files are all correct.

@mpacer , can you fix this?

**Comment by mpacer** [comment]
Fixed by 632bebb3c0d9176b2521ff6752a2fcfbe4dc7696.
